"""feat: agregar campo password a usuarios

Revision ID: 6188f50d9e95
Revises: 6b10a2462f0d
Create Date: 2026-03-15 18:13:39.362264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6188f50d9e95'
down_revision: Union[str, Sequence[str], None] = '6b10a2462f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'password')
    # ### end Alembic commands ###
